[image]
width = 400
output = "img.ppm"

[camera]
aspect_ratio = "16:9"
field_of_view = 40
position = "0, 0.2, 0.3"
look_at = "0, 0.1, 0"

[renderer]
samples_per_pixel = 20
max_bounces = 10

[sky]
type = "linear-gradient"
from = "1, 1, 1"
to = "0.5, 0.7, 1"

[[materials]]
type = "lambertian"
name = "matte"
albedo = "0.8, 0.9, 0.8"

[[materials]]
type = "lambertian"
name = "ground"
albedo = "0.8, 0.8, 0"

[[objects]]
type = "sphere"
position = "0, -100.5, -1"
radius = 100
material = "ground"

[[objects]]
type = "mesh"
path = "./bunny.obj"
material = "matte"
